src: {
  root: index.tsx\n(root file) {tooltip: call setRouterBaseRoute here}
  routes: {
    tooltip: all routes component should not have any parameters\nall route optional parameters should be at the end of the path
    index: index.tsx\n(Main Layout) {tooltip: requires the call of useRoutes only if render made with react and MainLayout's render depending on current route or loading state}
    home: index.index.tsx\n(Home Page)
    notFound: 404.tsx\n(Not Found Page)
  }
}
